// Action Types
export const TOGGLE_LOADING_SPINNER_OFF = "TOGGLE_LOADING_SPINNER_OFF";
export const TOGGLE_LOADING_SPINNER_ON = "TOGGLE_LOADING_SPINNER_ON";
export const UPDATE_START_SEARCH_DATE = "UPDATE_START_SEARCH_DATE";
export const UPDATE_END_SEARCH_DATE = "UPDATE_END_SEARCH_DATE";
export const UPDATE_LEAGUE_SELECTION = "UPDATE_LEAGUE_SELECTION";
